name = input('input your name:')
age = input('input your age:')
Reg = input('input your Reg No:')
dept = input('input your Department:')
r = int(input('input the radius of the circle:'))
area = str((22/7) * r * r)
print('Name: '+ name)
print('Age: '+ age)
print('Reg No: '+ Reg)
print('Department: '+ dept)
print('The area of the circle is: '+ area)